project:
  type: website
  output-dir: docs
  
website:
  title: "Data Science blog project"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/JacobBrown6908
      - icon: linkedin
        href: www.linkedin.com/in/jacob-brown-9230582aa
format:
  html:
    theme: cosmo
    css: styles.css



